name: Godot Export für Raspberry Pi

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write


jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Godot Headless 4.4.1 herunterladen
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          unzip Godot_v4.4.1-stable_linux.x86_64.zip
          mv Godot_v4.4.1-stable_linux.x86_64 godot

      - name: Godot Export-Templates 4.4.1 herunterladen
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          unzip -o Godot_v4.4.1-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/4.4.1.stable/

      - name: Templates in directory verschieben
        run: |
          mv ~/.local/share/godot/export_templates/4.4.1.stable/templates/* ~/.local/share/godot/export_templates/4.4.1.stable/
          rmdir ~/.local/share/godot/export_templates/4.4.1.stable/templates

      - name: Export-Zielverzeichnis anlegen
        run: mkdir -p build

      - name: Exportiere für Raspberry Pi
        run: |
          chmod +x ./godot
          ./godot --headless --export-release "Raspberry Pi" build/game_rpi

      - name: Raspberry Pi Build als Artifact hochladen
        uses: actions/upload-artifact@v4
        with:
          name: RetteDasSchulfest-RPi
          path: build/game_rpi

      - name: Exportiere für Windows
        run: |
          ./godot --headless --export-debug "Windows Desktop" build/game_windows_debug.exe

      - name: Windows Build als Artifact hochladen
        uses: actions/upload-artifact@v4
        with:
          name: RetteDasSchulfest-Debug-Windows
          path: build/game_windows_debug.exe

      - name: Upload Build to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: 'Nightly Build'
          files: |
            build/game_rpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
